-- CAPITULO 10, EJERCICIO 2
-- Adalberto Cerrillo Vazquez

CREATE TABLE CLIENTE_ACV(
   ID_CLIENTE NUMBER(6) CONSTRAINT CLIENTE_ACV_PK PRIMARY KEY,
   NOMBRE VARCHAR2(35) CONSTRAINT CLIENTE_NOM_NN NOT NULL,
   APELLIDO_PATERNO VARCHAR2(25) CONSTRAINT CLIENTE_APP_NN NOT NULL,
   APELLIDO_MATERNO VARCHAR2(25),
   COLONIA VARCHAR2(30) CONSTRAINT CLIENTE_COL_NN NOT NULL,
   CALLE VARCHAR2(30) CONSTRAINT CLIENTE_CALLE_NN NOT NULL,
   TELEFONO CHAR(10) CONSTRAINT CLIENTE_TEL_NN NOT NULL
);

CREATE TABLE AGENCIA_ACV(
   ID_AGENCIA NUMBER(4) CONSTRAINT AGENCIA_ACV_PK PRIMARY KEY,
   COLONIA VARCHAR2(30) CONSTRAINT AGENCIA_COL_NN NOT NULL,
   CALLE VARCHAR2(30) CONSTRAINT AGENCIA_CALLE_NN NOT NULL,
   TELEFONO CHAR(10) CONSTRAINT AGENCIA_TEL_NN NOT NULL
);

CREATE TABLE EMPLEADO_ACV(
   ID_EMPLEADO NUMBER(6) CONSTRAINT EMPLEADO_ACV_PK PRIMARY KEY,
   NOMBRE VARCHAR2(35) CONSTRAINT EMPLEADO_NOM_NN NOT NULL,
   APELLIDO_PATERNO VARCHAR2(25) CONSTRAINT EMPLEADO_APP_NN NOT NULL,
   APELLIDO_MATERNO VARCHAR2(25),
   TELEFONO CHAR(10) CONSTRAINT EMPLEADO_TEL_NN NOT NULL,
   ID_AGENCIA NUMBER(6),
   CONSTRAINT AG_ACV_EMP_ACV_FK FOREIGN KEY (ID_AGENCIA) REFERENCES AGENCIA_ACV(ID_AGENCIA)
);

CREATE TABLE CATEGORIA_ACV(
   ID_CATEGORIA NUMBER (3) CONSTRAINT CATEGORIA_ACV_PK PRIMARY KEY,
   DESCRIPCION VARCHAR2 (50) CONSTRAINT CAT_DESCRIPCION_NN NOT NULL,
   IVA NUMBER (2) CONSTRAINT CATEGORIA_IVA_NN NOT NULL
);

CREATE TABLE HOTEL_ACV(
   ID_HOTEL NUMBER(6) CONSTRAINT HOTEL_ACV_PK PRIMARY KEY,
   FECHA_CONSTRUCCION DATE CONSTRAINT HOTEL_FC_NN NOT NULL,
   NOMBRE VARCHAR2(35) CONSTRAINT HOTEL_NOM_NN NOT NULL,
   TELEFONO CHAR(10) CONSTRAINT HOTEL_TEL_NN NOT NULL,
   COLONIA VARCHAR2(30) CONSTRAINT HOTEL_COL_NN NOT NULL,
   CALLE VARCHAR2(30) CONSTRAINT HOTEL_CALLE_NN NOT NULL,
   ID_CATEGORIA NUMBER(3),
   CONSTRAINT CAT_HOTEL_ACV_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_ACV(ID_CATEGORIA)
);

CREATE TABLE TIPO_HABITACION_ACV(
   ID_TIPO NUMBER (3) CONSTRAINT TIPO_HAB_ACV_PK PRIMARY KEY,
   DESCRIPCION VARCHAR2 (50) CONSTRAINT TIPO_HAB_DESC_NN NOT NULL
);

CREATE TABLE HABITACION_ACV(
   ID_HABITACION NUMBER(6) CONSTRAINT HABITACION_ACV_PK PRIMARY KEY,
   NOMBRE VARCHAR2(30) CONSTRAINT HABITACION_NOM_NN NOT NULL,
   ID_TIPO NUMBER(3),
   CONSTRAINT TIPO_HAB_HAB_ACV_FK FOREIGN KEY (ID_TIPO) REFERENCES TIPO_HABITACION_ACV(ID_TIPO)
);

CREATE TABLE HABITACION_HOTEL_ACV(
   ID_HOTEL NUMBER(6),
   ID_HABITACION NUMBER(6),
   CANTIDAD NUMBER(3) CONSTRAINT HAB_HOT_ACV_CK CHECK (CANTIDAD>0),
   CONSTRAINT HAB_HOT_ACV_PK PRIMARY KEY (ID_HOTEL, ID_HABITACION),
   CONSTRAINT HAB_HAB_HOT_ACV_FK FOREIGN KEY (ID_HABITACION) REFERENCES HABITACION_ACV(ID_HABITACION),
   CONSTRAINT HOT_HAB_HOT_ACV_FK FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL_ACV(ID_HOTEL)
);

CREATE TABLE RESERVA_ACV(
   ID_RESERVA NUMBER (6),
   ID_CLIENTE NUMBER(6),
   ID_EMPLEADO NUMBER(6),
   ID_HOTEL NUMBER(6),
   ID_HABITACION NUMBER(6),
   FECHA_INICIO DATE CONSTRAINT RESERVA_ACV_FI_NN NOT NULL,
   FECHA_FIN DATE CONSTRAINT RESERVA_ACV_FF_NN NOT NULL,
   PRECIO NUMBER(6) CONSTRAINT RESERVA_ACV_PRECIO_CK CHECK (PRECIO>0),
   CONSTRAINT RESERVA_ACV_PK PRIMARY KEY (ID_RESERVA, ID_CLIENTE, ID_EMPLEADO, ID_HOTEL, ID_HABITACION),
   CONSTRAINT CLI_ACV_RES_ACV_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_ACV(ID_CLIENTE),
   CONSTRAINT EMP_ACV_RES_ACV_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO_ACV(ID_EMPLEADO),
   CONSTRAINT HAB_HOT_ACV_RES_FK FOREIGN KEY (ID_HOTEL,ID_HABITACION) REFERENCES HABITACION_HOTEL_ACV(ID_HOTEL,ID_HABITACION)
);


-------------------------------------------------------- SEQUENCES

CREATE SEQUENCE CLIENTE_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
CREATE SEQUENCE AGENCIA_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
CREATE SEQUENCE EMPLEADO_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
CREATE SEQUENCE CATEGORIA_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
CREATE SEQUENCE HOTEL_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
CREATE SEQUENCE TIPO_HAB_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
CREATE SEQUENCE HABITACION_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
CREATE SEQUENCE RESERVA_ID_ACV_SEQ 
       INCREMENT BY 1
       START WITH 1
       NOMAXVALUE
       NOMINVALUE
       NOCACHE
       NOCYCLE;
       
-----------------------------------------------------------------------SYNONYMS

CREATE SYNONYM CLI FOR CLIENTE_ACV;
CREATE SYNONYM AG FOR AGENCIA_ACV;
CREATE SYNONYM EP FOR EMPLEADO_ACV;
CREATE SYNONYM CT FOR CATEGORIA_ACV;
CREATE SYNONYM HT FOR HOTEL_ACV;
CREATE SYNONYM TH FOR TIPO_HABITACION_ACV;
CREATE SYNONYM HB FOR HABITACION_ACV;
CREATE SYNONYM HH FOR HABITACION_HOTEL_ACV;
CREATE SYNONYM RS FOR RESERVA_ACV;


--------------------------------------------------------------------- INDEXES
       
CREATE INDEX AG_ACV_COL_IDEXX ON AGENCIA_ACV(COLONIA);
CREATE INDEX CLI_ACV_AP_INDEX ON CLIENTE_ACV(APELLIDO_PATERNO);
CREATE INDEX CLI_ACV_AM_INDEX ON CLIENTE_ACV(APELLIDO_MATERNO);
CREATE INDEX CLI_ACV_COL_INDEX ON CLIENTE_ACV(COLONIA);
CREATE INDEX EP_ACV_AP_INDEX ON EMPLEADO_ACV(APELLIDO_PATERNO);
CREATE INDEX EP_ACV_AM_INDEX ON EMPLEADO_ACV(APELLIDO_MATERNO);
CREATE INDEX EP_ACV_AG_INDEX ON EMPLEADO_ACV(ID_AGENCIA);
CREATE INDEX HB_ACV_TIPO_INDEX ON HABITACION_ACV(ID_TIPO);
CREATE INDEX HH_ACV_CANTIDAD_INDEX ON HABITACION_HOTEL_ACV(CANTIDAD);
CREATE INDEX HT_ACV_COLONIA_INDEX ON HOTEL_ACV(COLONIA);
CREATE INDEX HT_ACV_CAT_INDEX ON HOTEL_ACV(ID_CATEGORIA);
CREATE INDEX RES_ACV_CLI_INDEX ON RESERVA_ACV(ID_CLIENTE);
CREATE INDEX RES_ACV_EMP_INDEX ON RESERVA_ACV(ID_EMPLEADO);
CREATE INDEX RES_ACV_HOTEL_INDEX ON RESERVA_ACV(ID_HOTEL);
CREATE INDEX RES_ACV_HB_INDEX ON RESERVA_ACV(ID_HABITACION);
CREATE INDEX RES_ACV_PRECIO_INDEX ON RESERVA_ACV(PRECIO);