DESC REGIONS;
DESC COUNTRIES;
DESC LOCATIONS;
DESC JOBS;
DESC JOB_HISTORY;
DESC EMPLOYEES;
DESC DEPARTMENTS;


SELECT * FROM  REGIONS;
SELECT * FROM COUNTRIES;
SELECT * FROM LOCATIONS;
SELECT * FROM JOBS;
SELECT * FROM JOB_HISTORY;
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
