-- Ejercicio 1 del Capitulo 11
-- Adalberto Cerrillo Vazquez


-- Creando las secuencias necesarias para las tablas RH

CREATE SEQUENCE REGIONS_ID_SEQ_ACV
     INCREMENT BY 1
     START WITH 5
     NOMAXVALUE
     NOMINVALUE
     NOCACHE
     NOCYCLE;
     
CREATE SEQUENCE LOCATIONS_ID_SEQ_ACV
    INCREMENT BY 100
    START WITH 3300
    NOMAXVALUE
    NOMINVALUE
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE EMPLOYEE_ID_SEQ_ACV
   INCREMENT BY 1
   START WITH 207
   NOMAXVALUE
   NOMINVALUE
   NOCACHE
   NOCYCLE;
   
CREATE SEQUENCE C
   INCREMENT BY 10
   START WITH 280
   NOMAXVALUE
   NOMINVALUE
   NOCACHE
   NOCYCLE;
   
------------------------------------------------------Synonims

CREATE SYNONYM PS FOR PAIS_ACV; 
CREATE SYNONYM DP FOR DEPARTAMENTO_ACV;
CREATE SYNONYM EP FOR EMPLEO_ACV;
CREATE SYNONYM EPDO FOR EMPLEADO_ACV;
CREATE SYNONYM REG FOR REGION_ACV;
CREATE SYNONYM REG_EP FOR REGISTRO_EMPLEO_ACV;
CREATE SYNONYM UB FOR UBICACION_ACV;


-------------------------------------------------------- INDEX

CREATE INDEX PAIS_ACV_NOM_INDEX ON PAIS_ACV(NOMBRE_PAIS);
CREATE INDEX PAIS_ACV_IDREGION_INDEX ON PAIS_ACV(ID_REGION);
CREATE INDEX UB_ACV_CALLE_INDEX ON UBICACION_ACV(CALLE);
CREATE INDEX UB_ACV_CIUDAD_INDEX ON UBICACION_ACV(CIUDAD);
CREATE INDEX UB_ACV_EST_INDEX ON UBICACION_ACV(ESTADO);
CREATE INDEX UB_ACV_PAIS_INDEX ON UBICACION_ACV(ID_PAIS);
CREATE INDEX EMP_ACV_AP_INDEX ON EMPLEADO_ACV(APELLIDO);
CREATE INDEX EMP_ACV_EMP_INDEX ON EMPLEADO_ACV(ID_EMPLEO);
CREATE INDEX EMP_ACV_GER_INDEX ON EMPLEADO_ACV(ID_GERENTE);
CREATE INDEX EMP_ACV_DEP_INDEX ON EMPLEADO_ACV(ID_DEPARTAMENTO);
CREATE INDEX DEP_ACV_GER_INDEX ON DEPARTAMENTO_ACV(ID_GERENTE);
CREATE INDEX DEP_ACV_UB_INDEX ON DEPARTAMENTO_ACV(ID_UBICACION);
CREATE INDEX REGEMP_ACV_EMPLE_IDX ON REGISTRO_EMPLEO_ACV(ID_EMPLEADO);
CREATE INDEX REGEMP_ACV_EMP_INDEX ON REGISTRO_EMPLEO_ACV(ID_EMPLEO);
CREATE INDEX REGEMP_ACV_DEP_INDEX ON REGISTRO_EMPLEO_ACV(ID_DEPARTAMENTO);

---------------------------------------------------------------------- TABLAS

CREATE TABLE REGION_ACV(
   ID_REGION NUMBER CONSTRAINT REG_ACV_PK PRIMARY KEY,
   NOMBRE_REGION VARCHAR2(25)
);

CREATE TABLE PAIS_ACV(
   ID_PAIS CHAR(2) CONSTRAINT PAIS_ACV_PK PRIMARY KEY,
   NOMBRE_PAIS VARCHAR2(40),
   ID_REGION NUMBER,
   CONSTRAINT REG_ACV_PAIS_ACV_FK FOREIGN KEY (ID_REGION) REFERENCES REGION_ACV(ID_REGION)
);

CREATE TABLE UBICACION_ACV(
   ID_UBICACION NUMBER(4) CONSTRAINT UB_ACV_PK PRIMARY KEY,
   CALLE VARCHAR2(40),
   CODIGO_POSTAL VARCHAR2(12),
   CIUDAD VARCHAR2(30) CONSTRAINT UB_ACV_CD_NN NOT NULL,
   ESTADO VARCHAR(25),
   ID_PAIS CHAR(2),
   CONSTRAINT PAIS_ACV_UB_ACV_FK FOREIGN KEY (ID_PAIS) REFERENCES PAIS_ACV(ID_PAIS)
);

CREATE TABLE DEPARTAMENTO_ACV(
   ID_DEPARTAMENTO NUMBER(4) CONSTRAINT DEP_ACV_PK  PRIMARY KEY,
   NOMBRE_DEPARTAMENTO VARCHAR(30) CONSTRAINT DEP_ACV_NOM_NN NOT NULL,
   ID_GERENTE NUMBER(6),
   ID_UBICACION NUMBER(4),
   CONSTRAINT UB_ACV_DEP_ACV_FK FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION_ACV(ID_UBICACION)
);

CREATE TABLE EMPLEADO_ACV(
   ID_EMPLEADO NUMBER(6) CONSTRAINT EMP_ACV_PK PRIMARY KEY,
   NOMBRE VARCHAR2(20),
   APELLIDO VARCHAR2(25) CONSTRAINT EMP_ACV_APE_NN NOT NULL,
   CORREO VARCHAR2(25) CONSTRAINT EMP_ACV_CORR_NN NOT NULL CONSTRAINT EMP_ACV_CORR_UQ UNIQUE,
   TELEFONO VARCHAR2(20),
   FECHA_CONTRATACION DATE CONSTRAINT EMP_FC_NN NOT NULL,
   ID_EMPLEO VARCHAR2(10),
   SALARIO NUMBER(8,2) CONSTRAINT EMP_SAL_CK CHECK (SALARIO>0),
   COMISION_PV NUMBER(2,2),
   ID_GERENTE NUMBER(6),
   ID_DEPARTAMENTO NUMBER(4),
   CONSTRAINT EMPLEO_EMP_FK FOREIGN KEY(ID_EMPLEO) REFERENCES EMPLEO_ACV(ID_EMPLEO),
   CONSTRAINT DEP_ACV_EMP_ACV_FK FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO_ACV(ID_DEPARTAMENTO)
);

ALTER TABLE EMPLEADO_ACV ADD ID_GERENTE NUMBER(6);
ALTER TABLE EMPLEADO_ACV ADD CONSTRAINT EMP_ACV_EMP_ACV_FK FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADO_ACV(ID_EMPLEADO);
ALTER TABLE DEPARTAMENTO_ACV ADD CONSTRAINT EMP_DEP_ACV_FK FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADO_ACV(ID_EMPLEADO);
ALTER TABLE REGISTRO_EMPLEO_ACV ADD CONSTRAINT REG_EMP_PK PRIMARY KEY (ID_EMPLEADO, FECHA_INICIO);

CREATE TABLE EMPLEO_ACV(
   ID_EMPLEO VARCHAR2(10) CONSTRAINT EMPLEO_ACV_PK PRIMARY KEY,
   NOMBRE_EMPLEO VARCHAR2(35) CONSTRAINT EMPLEO_NOM_NN NOT NULL,
   SALARIO_MINIMO NUMBER(6),
   SALARIO_MAXIMO NUMBER(6)
);

CREATE TABLE REGISTRO_EMPLEO_ACV(
   ID_EMPLEADO NUMBER(6),
   FECHA_INICIO DATE CONSTRAINT EMP_SD_ACV_NN NOT NULL,
   FECHA_FINAL DATE CONSTRAINT EMP_ED_ACV_NN NOT NULL,
   ID_EMPLEO VARCHAR2(10),
   ID_DEPARTAMENTO NUMBER(4),
   CONSTRAINT EMP_ACV_INTERVALO_CK CHECK (FECHA_FINAL > FECHA_INICIO),
   CONSTRAINT EMP_ACV_REG_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO_ACV(ID_EMPLEADO),
   CONSTRAINT EMPLEO_ACV_REG_FK FOREIGN KEY (ID_EMPLEO) REFERENCES EMPLEO_ACV(ID_EMPLEO),
   CONSTRAINT DEP_ACV_REG_FG FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO_ACV(ID_DEPARTAMENTO)
);